version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12341234"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - postgres
      - mongo

  web:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py migrate --database sync_mongo &&
        python manage.py runserver
      "
    environment:
      RANKING_INTERVAL: 300
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12341234"
      POSTGRES_NAME: "ms_cinema"
      MONGO_NAME: "ms_cinema"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  postgres_data:
