# Generated by Django 4.1.8 on 2023-04-18 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("protagonists", models.CharField(default="", max_length=255)),
                ("poster", models.ImageField(upload_to="upload/movies/posters/")),
                ("start_time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CU", "Coming Up"),
                            ("ST", "Starting"),
                            ("RU", "Running"),
                            ("FN", "Finished"),
                        ],
                        default="CU",
                        max_length=2,
                    ),
                ),
                ("ranking", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["name"], name="movies_movi_name_98114c_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["ranking"], name="movies_movi_ranking_c70f8e_idx"
            ),
        ),
    ]
